### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mdjasper**
Hey this document is great. I'd like to propose this change to make it more clear. As it is currently written there is a single phrase which I believe is too broad in scope and would limit legitimate and positive conversations which are within the scope of this community.

>Examples of unacceptable behavior by participants include:
> ...
>Verbal or written comments related to gender, sexual orientation, disability, physical appearance, body size, race or religion

As I interpret this phrase, any discussion around the topics listed above is unacceptable. This would limit, for example,  discussions of gender around pay and equal treatment in the workplace, or discussions about accessibility or the needs of users with disabilities.

If this is clarified that the comments are negative in nature, or directed to an individual I believe it may be more helpful. I'm not sure if my verbiage is perfect, but maybe a good starting place?

### CODE REVIEW

**Comment by paniclater** [comment]
Really agree with this feedback. The react conf coc uses the following language:

>Harassment includes offensive verbal comments related to gender, sexual orientation, disability, physical appearance, body size, race, religion

I didn't see this PR and put another one up here after getting similar feedback that uses the same langauge they do: https://github.com/UtahJS/slack-coc/pull/3

**Comment by maddie927** [comment]
Oops, I also saw the other PR first. I left a wording suggestion as a comment there: https://github.com/UtahJS/slack-coc/pull/3#issuecomment-433959115

Maybe I'll open a 3rd PR :joy:

**Comment by mdjasper** [comment]
pr #3 is getting more traction, and accomplishes the same thing

**Comment by maddie927** [comment]
@mdjasper Sorry that happened, but thank you for reading the CoC carefully and participating!

**Pull request closed without merging**
